Script started on 2015年03月12日 (週四) 12時45分58秒
]0;F74036043@2015cpp: ~F74036043@2015cpp:~$ whoami; pwd
F74036043
/home/F74036043
]0;F74036043@2015cpp: ~F74036043@2015cpp:~$  git config ‐l[K[K[K[K -l
git: 'confi' is not a git command. See 'git --help'.

Did you mean this?
	config
]0;F74036043@2015cpp: ~F74036043@2015cpp:~$ whoami; pwd[K[K[K[K[K[K[K[K[K[K[Kgit cong[Khiig[K[K[K[Kfig -l
user.name=annie31123
user.email=patrick8589@gmail.com
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
]0;F74036043@2015cpp: ~F74036043@2015cpp:~$ git clone https://github.com/annie31123/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
]0;F74036043@2015cpp: ~F74036043@2015cpp:~$ exit

Script done on 2015年03月12日 (週四) 12時47分14秒
